### ISSUE TITLE
[3.2.2.3] Creation of Factory Pattern Diagram

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#149]
**What is the task about?** 
This task is focused on documenting the Factory Pattern Diagram.

**What are the goals of the task?** 
Ensure that the Factory Pattern Diagram has been done and documented properly. 

**Success or Completion Criteria:** 
Provide well-documented and up-to-date Factory Pattern Diagram. 

**Allocated time:** 3 days

**Start date and end date:** [Start Date: 15/11/23], [End Date: 17/11/23]

**Owner:** Han Xiang & Alain

**Status of the task:** To-Do

**Priority:** High

**Comment by KeeHanXiang** [comment]
Describe the work done in detail.
This task involves creating and documenting the Factory Pattern Diagram to accurately represent its usage in the project.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
Successfully completing this task ensures that a well-documented and up-to-date Factory Pattern Diagram is available.

Start date and end date:
[Start Date: 15/11/23]
[End Date: 17/11/23]

**Comment by ImUrGit** [comment]
Describe the work done in detail.
Helped in doing up the detailed design factory pattern and highlighted the before and after implementation of the design pattern to illustrate its usefulness.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
The documentation of the design patterns the team can use is important because it allows our client to see or professors to see an improvement in the structuring of our entities in our system.

Start date and end date:
[Start Date: 15/11/23]
[End Date: 17/11/23]
