### ISSUE TITLE
[3.5.1.1] References and Acknowledgement

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#152]
**What is the task about?** 
This task is focused on drafting the References and Acknowledgement for the M3 document.

**What are the goals of the task?** 
Create the introduction segment for the M3 report. 

**Success or Completion Criteria:** 
Compile and document all relevant references and acknowledgements, ensuring accuracy and completeness.

**Allocated time:** 1 day

**Start date and end date:** [Start Date: 09/11/23], [End Date: 09/11/23]

**Owner:** Alain & Yi San

**Status of the task:** To-Do

**Priority:** High

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
I assembled the References and Acknowledgements section for our M3 document. This task was crucial in crediting all the sources and individuals who have contributed to the success of our project. I thoroughly searched through our documentation and correspondence to identify all the references we used throughout our project development. Additionally, I drafted thoughtful acknowledgments to thank our collaborators, mentors, and anyone who provided support or feedback.


**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
Creating a detailed and accurate References and Acknowledgements section is vital for the integrity of our M3 document. It reflects our diligence in citing sources and expressing gratitude, which not only fulfills our academic and professional standards but also acknowledges the collective effort that has gone into our project.


**Start date and end date:**
[Start Date: 09/11/23]
[End Date: 09/11/23]

**Comment by ImUrGit** [comment]
Describe the work done in detail.
I have helped Yi San in collating the references and acknowledgement section for the Milestone 3 document. 

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
It is important to reference and acknowledge when it is due because it is basic manners.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 09/11/23]
