### ISSUE TITLE
[3.4.2] Reviewed Functional Requirements

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#159]
**What is the task about?** 
This task is focused on reviewing Functional Requirements.

**What are the goals of the task?** 
Successfully review and validated Functional Requirements for accuracy and completeness. 

**Success or Completion Criteria:** 
Complete a thorough review of Functional Requirements, address any identified discrepancies, and ensure alignment with objectives set by stakeholder. 

**Allocated time:** 2 days

**Start date and end date:** [Start Date: 15/11/23], [End Date: 16/11/23]

**Owner:** Alain & Yi San

**Status of the task:** To-Do

**Priority:** High

**Comment by lowyisan** [comment]
**Describe the work done in detail.**
I engaged in a meticulous review of the Functional Requirements as specified by our stakeholders. This task involved scrutinizing each requirement to validate its accuracy and ensure completeness in the context of the system's capabilities. I examined how our current implementation aligns with these requirements, checking for feature completeness and proper function behaviors as expected by the stakeholders.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
A thorough review of the Functional Requirements is a key success factor for our project's acceptance criteria. By rigorously comparing our implementation against these requirements, we can confidently identify areas that meet the success criteria and areas that may require further work. Addressing and resolving any identified discrepancies will bring us closer to fulfilling the project's objectives and satisfying stakeholder expectations.

**Start date and end date:**
[Start Date: 14/11/23]
[End Date: 15/11/23]

**Comment by ImUrGit** [comment]
Describe the work done in detail.
I have worked in making sure that the functional requirements stated by the client meet the expectations and align with the client. I have also tried to go through each functional requirement and run it through with the team in order to make sure that we have the clients expectations on our mind.

Has this work been committed to the repository?
The work does not involve any code. Therefore, no repository commits is needed.

How does the work affect success or completion criteria?
It is important to review the requirements from time to time because we, the team have to remember that we are working for the client and we want to be able to meet the clients expectation. 

Start date and end date:
[Start Date: 14/11/23]
[End Date: 15/11/23]
