### ISSUE TITLE
[3.1.1] Change in Gantt Chart

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#163]
**What is the task about?** 
This task is to revise changes to the gantt chart as we have been given the requirements for M3.

**What are the goals of the task?**

Revise Gantt Chart

**Success or completion criteria:**

Completed the revisions to the Gantt Chart

**Allocated time:** 3 days

**Start date and end date:** [Start Date: 09/11/23], [End Date: 11/11/23]

**Owner:** Isaac

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
Worked on the GANTT chart as well as the scheduling for the project's M3 deliverable.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
This aligns the team to a scheduled timeline for the process of submitting the deliverable. 

Start date and end date:
[Start Date: 09/11/23]
[End Date: 11/11/23]

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Was responsible for tasks related to the GANTT chart and scheduling, specifically for the M3 project deliverable.

**Has this work been committed to the repository?**
Since this work doesn't involve code changes, there is no need for any commits to the repository.

**How does the work affect success or completion criteria?**
This work plays a crucial role in aligning the team with a well-defined timeline for the successful submission of the deliverable.

Start date and end date:
[Start Date: 09/11/23]
[End Date: 11/11/23]
