### ISSUE TITLE
[3.5.4] Project Prototype & Wireframes

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#166]
**What is the task about?** 
This task is focused on the documentation of the created project prototype & wireframes.

**What are the goals of the task?** 
Successfully document the project prototypes and wireframes, ensuring clarity and completeness. 

**Success or Completion Criteria:** 
Complete comprehensive documentation covering the project prototype and wireframes, addressing all key components and design elements. 

**Allocated time:** 5 days

**Start date and end date:** [Start Date: 18/11/23], [End Date: 22/11/23]

**Owner:** Isaac & Michelle

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail.**
I documented the project prototypes and wireframes, providing detailed descriptions that align with the respective Product Features (PFs) and Functional Requirements (FRs). This effort focuses on elucidating the functionalities of the prototypes beyond their UI, offering an even more comprehensible understanding.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
Instead of merely addressing the visual aspects, the detailed descriptions enhance comprehension and facilitate effective communication within the project team. 

Start date and end date:
[Start Date: 18/11/23]
[End Date: 22/11/23]

**Comment by mvchello** [comment]
**Describe the work done in detail.**
The task involved the comprehensive documentation of project prototypes and wireframes. The documentation included detailed descriptions that align with specific Use Cases (UCs)Product Features (PFs) and Functional Requirements (FRs). This effort aimed to provide a deeper understanding of the prototypes' functionalities beyond their user interfaces, enhancing clarity.

**Has this work been committed to the repository?**
The work does not involve any code. Therefore, no repository commits is needed.

**How does the work affect success or completion criteria?**
Instead of exclusively focusing on visual elements, the detailed descriptions play a crucial role in enhancing understanding and facilitating clear communication among the project team. This level of clarity is essential for the project's success and ensuring alignment with the established completion criteria.

Start date and end date:
[Start Date: 18/11/23]
[End Date: 22/11/23]
