### ISSUE TITLE
[1.2.2] Revision of Requirement Analysis

### ISSUE THREAD

**Issue by lowyisan** [lowyisan/INF2001_P6-6#19]
**Task title ID:** #17

**What is the task about?** This task requires the team to go through the list of requirements that have been generated. They are to ensure that the requirements corroborate with what has been discussed with the client through the meeting and follow-up.

**What are the goals of the task?** The goal of this task is to ensure that the team is on the right track with the right set of requirements in mind when planning how to go forth with the project.

**Success or completion criteria:** The success of this task is determined through the unison understanding of requirements needed by the client for the project to move forward.

**Allocated time:** 6 days

**Start date and end date:** [Start Date: 07/09/23], [End Date: 12/09/23]

**Owner:** Alain & Yi San

**Status of the task:** Completed

**Priority:** Medium

**Comment by lowyisan** [comment]
**Describe the work done in detail:**
During this task, we conducted a thorough review of the initial requirement analysis. We identified areas that required modification or refinement based on feedback from the client and the project team. We also addressed any ambiguities or inconsistencies in the requirements and made necessary updates to ensure they accurately reflect the project's goals.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
The revision of the requirement analysis is a critical step in ensuring that the project aligns with the client's needs and expectations. By addressing any issues or gaps in the initial analysis, we enhance the clarity and accuracy of the project requirements. This, in turn, contributes to the successful completion of the project within scope and on time.

Start date and end date:
Start Date: 07/09/23
End Date: 12/09/23

**Comment by ImUrGit** [comment]
**Describe the work done in detail:**
During this task, I have helped in doing a thorough review of the initial requirement analysis. I have also helped in identifying areas that required modification or refinement based on feedback from the client and the project team. I have discussed with Yi san and the team in addressing any ambiguities or inconsistencies in the requirements and made necessary updates to ensure the team accurately reflect the project's goals.

**Has this work been committed to the repository?**
No, this task do not involve code changes. Therefore, no commits were made to the repository for this task.

**How does the work affect success or completion criteria?**
It is important to be able to discuss with the team and to analyse what the requirements are. This is because we need to refine and modify feedback from client in order to get the best version of the requirements. It will ultimately help the team to align our expectations with the client.

Start date and end date:
Start Date: 07/09/23
End Date: 12/09/23
