### ISSUE TITLE
[2.1.1] Changes in User Interface Requirements

### ISSUE THREAD

**Issue by KeeHanXiang** [lowyisan/INF2001_P6-6#40]
Task title ID: #40

What is the task about? This task involves revising the changes in the user interface requirements that were established in the M1 report.

What are the goals of the task?  

- Review the existing user interface requirements mentioned in the M1 report and clarify any ambiguities or inconsistencies. Ensure that all requirements are well-defined and understandable.
- Ensure that the revised requirements align with the needs and expectations of the end-users. 
- Ensure that the revised requirements are documented in a clear and organized manner. This documentation should be easily accessible to all relevant stakeholders.

Success or completion criteria: 

- To finish making changes to the user interface requirements

Allocated time: 3 days

Start date and end date: [Start Date: 16/10/23], [End Date: 18/10/23]

Owner: Alain

Status of the task: To-Do

Priority: Medium

**Comment by ImUrGit** [comment]
**Describe the work done in detail.**
Finished revising the changes in the user interface requirements. 


**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
It is important to change from the feedback received from the M1 report. This is so that the document will be much clearer and more in line with the client's needs.

**Start date and end date:**
[Start Date: 16/10/23]
[End Date: 18/10/23]
