### ISSUE TITLE
[1.4.4.2] Project Management

### ISSUE THREAD

**Issue by Magic1sarap** [lowyisan/INF2001_P6-6#63]
**Task title ID:** #42

**What is the task about?** To Oversee and coordinate all aspects of the project specifically M1, including planning, scheduling, resource allocation as well as communication to ensure its successful execution delivery within scope and the time constraints. 

**What are the goals of the task?** To ensure the M1 document is well-planned and efficiently executed while meeting the scope, time and other targets while maintaining effective communication within the team. 

**Success or completion criteria:** The successful completion of this task entails delivering the M1 document on time as well as within its scope. 

**Allocated time:** 4 days

**Start date and end date:** [Start Date: 16/09/23], [End Date: 19/09/23]

**Owner:** Isaac & Michelle

**Status of the task:** To-Do

**Priority:** High

**Comment by Magic1sarap** [comment]
**Describe the work done in detail:**
The work done includes the deliberation and justification of the chosen SDLC for the project, as well as including it in the M1 document. 

**Has this work been committed to the repository?**
No, as this task does not involve code. 

**How does the work affect success or completion criteria?**
This justifies or provides the rationale behind the chosen SDLC which should provide a framework for the project's direction. 

Start date and end date:
Start Date: 16/09/23
End Date: 19/09/23

**Comment by mvchello** [comment]
**Describe the work done in detail:**
A Work Breakdown Structure and Gantt chart were created in order to keep track of the progress of the project. These planning tools are essential in ensuring that there is proper work allocation amongst the team members so as to achieve constant advancements in the project.

**Has this work been committed to the repository?**
No, as this task does not involve code. 

**How does the work affect success or completion criteria?**
The work done affects the success of the project as without it, there would be no proper work allocation, and the progress of the project cannot be kept in check easily.

Start date and end date:
Start Date: 16/09/23
End Date: 19/09/23
