### ISSUE TITLE
[2.2.2] Creation of Component Diagram

### ISSUE THREAD

**Issue by mvchello** [lowyisan/INF2001_P6-6#94]
What is the task about? The task involves the documenting of the component diagram in detail.

What are the goals of the task? The primary goal is to visually represent the key components and their relationships within the software system, aiding in the understanding of the system's architecture.

Success or Completion Criteria: The section must effectively convey the architecture and design of the software system.

Allocated time: 6 days

Start date and end date: [Start Date: 23/10/23], [End Date: 28/10/23]

Owner: Alain & Michelle

Status of the task: To-Do

Priority: Medium

**Comment by ImUrGit** [comment]
**Describe the work done in detail:** I have worked together with Michelle to come up with the component diagram. We have referred to the class diagram and grouped BCE classes together to form different components.

**Has this work been committed to the repository?** No, there is no need to commit this work to the repository as it is done on the project board.

**How does the work affect success or completion criteria?** This affects the completion criteria because it is directly involved in the goals of the task set, which is to essentially create a component diagram.

**Start Date:** 23/10/23, **End Date:** 28/10/23

**Comment by mvchello** [comment]
**Describe the work done in detail.**
Together with Alain, the components diagram has been drafted with reference to the overall class diagram. Furthermore, grouping of the BCE classes was done to determine the components and connection of the component diagram.

**Has this work been committed to the repository?**
No work is needed to commit to the repository.

**How does the work affect success or completion criteria?**
As it is needed to visually present the key components and their relationship with one another, the completion of this task is crucial for the furtherment of the project, setting a direction/wireframe for the team to follow.

**Start date and end date:**
[Start Date: 23/10/23]
[End Date: 28/10/23]
